name: Convert Jupyter Notebooks to markdown and PDF

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
jobs:
  build:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with: 
          python-version: 3.x
      - name: Install Jupytext
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade jupytext
      - name: Convert Jupyter Notebooks to markdown
        run: |
          mkdir output
          for filename in code/*.ipynb; do jupytext --to md --update-metadata '{"jupytext": {"notebook_metadata_filter":"-all", "cell_metadata_filter":"-all"}}'; done
          cat code/*.md > output/result.md
      - uses: actions/upload-artifact@master
        with:
          name: output
          path: output
           
