name: Convert Jupyter Notebooks to Markdown and PDF

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
jobs:
  build:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with: 
          python-version: 3.x
      - name: Install Jupytext
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade jupytext
      - name: Convert Jupyter Notebooks to Markdown
        run: |
          mkdir output
          for filename in code/*.ipynb; do jupytext --to md --update-metadata '{"jupytext": {"notebook_metadata_filter":"-all", "cell_metadata_filter":"-all"}}' $filename; done
          cat code/*.md > output/result.md
      - name: Convert Markdown to PDF
        uses: docker://pandoc/latex:latest
        with:
          args: --output=output/manual.pdf --pdf-engine=xelatex --metadata-file=format/manual.yaml --template=docs/template/manual.latex output/result.md
      - uses: actions/upload-artifact@master
        with:
          name: manual
          path: output/manual.pdf
           
