name: convert

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
jobs:
  convert:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Concatenate Markdowns
        run: |
          mkdir output
          cat docs/content/*.md > output/bank_marketing.md
      - name: Convert Markdown to PDF
        uses: docker://pandoc/latex:latest
        with:
          args: --output=output/bank_marketing.pdf --pdf-engine=xelatex --metadata-file=docs/format/actions.yaml --template=docs/template/default.latex output/bank_marketing.md
      - uses: actions/upload-artifact@master
        with:
          name: bank_marketing.pdf
          path: output/bank_marketing.pdf
           
