name: Execute

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
jobs:
  execute:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout to git repository
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with: 
          python-version: 3.x
      - name: Install required packages
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest jupytext
          pip install --upgrade requirements.txt
      - name: Convert Jupyter Notebooks to Python files
        run: |
          mkdir output
          for filename in code/*.ipynb; do jupytext --to py --update-metadata '{"jupytext": {"notebook_metadata_filter":"-all", "cell_metadata_filter":"-all"}}' $filename; done
      - name: Test Python files
        run: |
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
           
